### ISSUE TITLE
Trouble with Algolia search

### ISSUE THREAD

**Issue by theapplegates** [creasoft-dev/fundamenty#3]
I am not able to get Algolia search to work. Not sure if it is operator error or not. 
In Chrome and Firefox the network tools don't show any communication with Algolia servers.
I am using Vercel.com to host and added the needed Algolia env vaules and nothing happens when I search.
Any ideas? They were added locally in the .env file and the search bar appeared like your 3RD_PARTY_SERVICES.md instructions.
Thanks
Paul

**Comment by theapplegates** [comment]
After following directions better I get this error when I invoke yarn fundamenty:tool init I get this error.

https://gist.github.com/theapplegates/a17e0b7ce1a4f53ef88182cc356ccff7

The code formatting is not working, so the gist has a copy of the error if you can't read the error below.

bobs:fundamenty thor2$ yarn fundamenty:tool init
yarn run v1.22.4
$ node ./tools/fundamenty-tool.js init
fundamenty-tool v.0.1 started with args ["init"]
(node:31354) UnhandledPromiseRejectionWarning: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 1:
    
    ^
    at generateError (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at Object.safeLoad (/Users/thor2/Documents/fundamenty/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at initProject (/Users/thor2/Documents/fundamenty/tools/fundamenty-tool.js:25:25)
    at /Users/thor2/Documents/fundamenty/tools/fundamenty-tool.js:59:9
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.14s.

**Comment by theapplegates** [comment]
I fixed my stupid error. The .yml file needed a space after each entry.
bobs:fundamenty thor2$ cat .fundamenty.yml
# Once you complete modifying this file, run
# $ yarn fundamenty:tool init
name: Fundamenty2
repoUrl: https://gitlab.com/creasoft-dev/projects/fundamenty
rootUrl: https://fundamenty-hheixkmdj.vercel.app
defaultLang: en
langs:
  - id: en
    name: English
  - id: es
    name: Español

WEB_ROOT_URL: http://localhost
ALGOLIA_APP_ID: XXX
ALGOLIA_INDEX_NAME: blog
ALGOLIA_SEARCH_API_KEY: xxx
ALGOLIA_ADMIN_API_KEY: xxxff9e8963d
GOOGLE_TAG_ID: xxx
DISQUS_SITE_NAME: xxx

But I still don't get anything pushed to Algolia.
I will work on it, I'm sure it's my fault.

**Comment by theapplegates** [comment]
Started fresh and all is working
